AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Layout/LineLength:
  Max: 140
  Exclude:
    - build/**/*.rb

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - build/**/*.rb

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Max: 175

Style/RegexpLiteral:
  EnforcedStyle: percent_r
  Enabled: true

Layout/EmptyLinesAroundArguments:
  Enabled: false

Naming/FileName:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - build/**/*.rb

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
