---
sudo: false
language: ruby
cache: bundler
dist: trusty
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
    - rvm: 2.1.9
      env: CHECK=test
    - rvm: 2.4.2
      env: CHECK=test_with_coveralls
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
