# Authentication
protected: true
user: puppet
pass: puppet

# Mcollective
client_cfg: "/etc/puppetlabs/mcollective/server.cfg"
client_timeout: "120"
use_mco_ruby: false
use_mcollective: false
discovery_timeout: '10'

# Slack Notifications
slack_webhook: false

# R10k
default_branch: production
ignore_environments: []
prefix_command: ''
r10k_deploy_arguments: "-pv"
allow_uppercase: true
command_prefix: 'umask 0022;'
